name: Update Language Statistics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 
jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stefvuck/github-profile-language-analytics@v1.1.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "pie, leaderboard"
      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update language statistics" || echo "No changes"
          git push
